services:
  - type: web
    name: horariocentros
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
